// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2023 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { UserAgency } from "@justice-counts/common/types";

/**
 * The DENY_LIST is our way of controlling whether or not an agency's dashboard is live and visible to the public.
 *
 *
 * `true` on this list means the agency will NOT have their dashboard live and visible
 * `false` on this list (* or not being on this list at all) means the agency will have their dashboard live and visible
 *
 * Note:
 *   - the DENY_LIST is temporary until we implement a backend solution
 *   - * this list contains only a snapshot of agencies at the time the switch from ALLOW_LIST to DENY_LIST
 *     took place
 *   - all newly created agencies moving forward will default to having a live and visible dashboard (and no need to include them on the list)
 *   - the purpose of this hardcoded list is to keep the existing agencies' dashboards hidden until they explicitly decide to
 *     go live with their dashboard
 */
export const DENY_LIST: Record<string, boolean> = {
  "22nd judicial circuit court": true,
  "aberdeen police department": true,
  "adams county sheriff's office": true,
  "administrative office of the illinois courts": true,
  "alabama department of corrections": true,
  "alaska department of corrections": true,
  "albany village police dept": true,
  "allen county sheriff's office": true,
  "amanda police department": true,
  "amelia police department": true,
  "american township police department": true,
  "ames police department": false,
  "amesville village police department": true,
  "andover police department": true,
  "ansonia police department": true,
  "arcanum police department": true,
  "arizona corrections [test]": true,
  "arizona court [test]": true,
  "arizona criminal justice commission": true,
  "arizona department of corrections": true,
  "rehabilitation & reentry": true,
  "arizona supervision [test]": true,
  "arizona supreme court": true,
  "adult probation services division": true,
  "arkansas department of correction": true,
  "arkansas division of community correction": true,
  "arkansas division of correction": true,
  "ashland county sheriff's office": true,
  "ashland police department": true,
  "ashley police department": true,
  "ashtabula county sheriff's office": true,
  "ashtabula police department": true,
  "athens county sheriff's office": true,
  "athens police department": true,
  "auglaize county sheriff's office": true,
  "baldwin wallace university safety and security office": true,
  "baltimore police department": true,
  "barnesville police department": true,
  "batavia police department": true,
  "bath township police department (allen)": true,
  "bay view police department": true,
  "bay village police department": true,
  "beachwood police department": true,
  "bedford heights police department": true,
  "bedford police department": true,
  "bellaire police department": true,
  "belmont county sheriff's office": true,
  "belmont police department": true,
  "bentleyville police department": true,
  "berea police department": true,
  "berlin heights police department": true,
  "bernalillo county metropolitan court": true,
  "bethel police department": true,
  "bethesda police department": true,
  "bexley police department": true,
  "blanchester police department": true,
  "blendon township police department": true,
  "bluffton police department": true,
  "bratenahl police department": true,
  "brecksville police department": true,
  "brice police department": true,
  "bridgeport police department": true,
  "broadview heights police department": true,
  "brooklyn heights police department": true,
  "brooklyn police department": true,
  "brook park police department": true,
  "brown county sheriff's office": true,
  "buchtel police department": true,
  "buckland police departmet": true,
  "bucyrus police department": true,
  "butler county metroparks police": true,
  "butler county sheriff's office": true,
  "cairo police department": true,
  "california department of corrections and rehabilitation": true,
  "carroll county sheriff's office": true,
  "carroll police department": true,
  "carrollton police department": true,
  "cass county court and pretrial services": true,
  "cass county sheriff’s department": true,
  "cass/pulaski community corrections": true,
  "castalia police department": true,
  "catawba police department": true,
  "catron county magistrate court in quemado": true,
  "catron county magistrate court in reserve": true,
  "cedar point police department": true,
  "center township police department": true,
  "chagrin falls police department": true,
  "champaign county sheriff's office": true,
  "chauncey police department": true,
  "chaves county magistrate court in roswell": true,
  "chief probation officers of california": true,
  "cibola county magistrae court in grants": true,
  "city of sandusky police department": true,
  "city of upper arlington police division": true,
  "city of vermilion police department": true,
  "clackamas county jail": true,
  "clark county park district police": true,
  "clark county sheriff's office": true,
  "clermont county sheriff's office": true,
  "cleveland heights police department": true,
  "cleveland lakefront state parks": true,
  "cleveland metroparks ranger police department": true,
  "cleveland municipal court probation department": true,
  "cleveland police department": true,
  "cleveland state university police department": true,
  "clinton county sheriff's office": true,
  "clinton township police department": true,
  "colfax county magistrate court in raton": true,
  "colfax county magistrate court in springer": true,
  "colorado department of corrections": true,
  "colorado department of public safety": true,
  "colorado judicial branch": true,
  "columbiana county sheriff's office": true,
  "columbiana police department": true,
  "columbus city attorney’s office": true,
  "columbus police department": true,
  "conneaut police department": true,
  "connecticut department of correction": true,
  "connecticut office of policy and management": true,
  "coolville marshal police department": true,
  "coshocton county sheriff's office": true,
  "coshocton police department": true,
  "crawford county sheriff's office": true,
  "cridersville police department": true,
  "curry county magistrate court in clovis": true,
  "cuyahoga community college campus police and security services": true,
  "cuyahoga county sheriff's office": true,
  "cuyahoga heights police department": true,
  "cuyahoga metropolitan housing authority": true,
  "darbydale police department": true,
  "darke county sheriff's office": true,
  "debaca county magistrate court in fort sumner": true,
  "defiance county sheriff's office": true,
  "defiance police department": true,
  "delaware county sheriff's office": true,
  "delaware department of correction": true,
  "delaware police department": true,
  "[delete] georgia judicial council and administrative office of the courts":
    true,
  "[delete] illinois criminal justice information authority (icja)": true,
  "dellroy marshal police department": true,
  "delphos police department": true,
  "[deprecated] north carolina department of public safety": true,
  "district of columbia department of corrections": true,
  "division of criminal and juvenile justice planning of the iowa department of human rights":
    true,
  "dona ana county magistrate court in anthony": true,
  "dona ana county magistrate court in hatch": true,
  "dona ana county magistrate court in las cruces": true,
  "donnelsville police department": true,
  "douglas county district attorney's office": true,
  "dublin police department": true,
  "east cleveland police department": true,
  "eastern ohio corrections center": true,
  "east liverpool police department": true,
  "east palestine police department": true,
  "eddy county magistrate court in artesia": true,
  "eddy county magistrate court in carlsbad": true,
  "eighth judicial district colfax county": true,
  "eighth judicial district taos county": true,
  "eighth judicial district union county": true,
  "eleventh judicial district mckinley county": true,
  "eleventh judicial district san juan county": true,
  "elida police department": true,
  "enon police department": true,
  "erie county sheriff's office": true,
  "erie metroparks police department and safety": true,
  "euclid police department": true,
  "fairfield county sheriff's office": true,
  "fairfield police department": true,
  "fairfield township police department": true,
  "fairview park police department": true,
  "fayette county sheriff's office": true,
  "fayetteville police department": true,
  "felicity police department": true,
  "fifth judicial district chaves county": true,
  "fifth judicial district eddy county": true,
  "fifth judicial district lea county": true,
  "first judicial district los alamos county": true,
  "first judicial district rio arriba county": true,
  "first judicial district santa fe county": true,
  "florida commission on offender review": true,
  "florida department of corrections": true,
  "flushing police department": true,
  "fort shawnee police department": true,
  "fourth judicial district guadalupe county": true,
  "fourth judicial district mora county": true,
  "fourth judicial district san miguel county": true,
  "franklin county common pleas court": true,
  "franklin county community based correctional facility": true,
  "franklin county metro park rangers": true,
  "franklin county municipal court": true,
  "franklin county prosecutor’s office": true,
  "franklin county public defender’s office": true,
  "franklin county sheriff's office": true,
  "franklin township police department": true,
  "gahanna division of police": true,
  "galena police department": true,
  "galion police department": true,
  "garfield heights police department": true,
  "gates mills police department": true,
  "geneva-on-the-lake police department": true,
  "geneva police department": true,
  "genoa township police department": true,
  "georgetown police department": true,
  "georgia department of community supervision": true,
  "georgia department of corrections": true,
  "georgia judicial council and administrative office of the courts": true,
  "german township police department (clark)": true,
  "glenwillow village police department": true,
  "glouster police department": true,
  "goshen township police (clermont)": true,
  "grandview heights division of police": true,
  "grant county magistrate court in bayard": true,
  "grant county magistrate court in silver city": true,
  "greater cleveland regional transit authority police department": true,
  "greenville police department": true,
  "grove city division of police": true,
  "groveport police department": true,
  "guadalupe county magistrate court in santa rosa": true,
  "hamersville police department": true,
  "hamilton police department": true,
  "hamilton township police department (franklin)": true,
  "hanoverton police department": true,
  "harding county magistrate court in roy": true,
  "harrisburg police department": true,
  "harrod police department": true,
  "hawaii department of public safety": true,
  "hawaii paroling authority": true,
  "hawaii state judiciary": true,
  "hayesville police department": true,
  "hicksville police department": true,
  "hidalgo county magistrate court in lordsburg": true,
  "higginsport police department": true,
  "highland heights police department": true,
  "highland hills police department": true,
  "hilliard division of police": true,
  "hocking college police department": true,
  "howard county community supervision": true,
  "howard county superior court": true,
  "hunting valley police department": true,
  "huron police association": true,
  "idaho criminal justice commission": true,
  "idaho department of correction": true,
  "illinois criminal justice information authority (icja)": true,
  "illinois department of corrections": true,
  "independence police department": true,
  "indiana department of correction": true,
  "indiana public defender commission": true,
  "iowa department of corrections": true,
  "iowa state university police department": true,
  "jacksonville police department": true,
  "jefferson police department": true,
  "jeromesville police department": true,
  "johnny appleseed park rangers": true,
  "johnson county district court": true,
  "johnson county prosecutor's office": false,
  "kansas department of corrections": true,
  "kelleys island police department": true,
  "kentucky department of corrections": true,
  "lake waynoka rangers": true,
  "lakewood police department": true,
  "lancaster police department": true,
  "law offices of the public defender": true,
  "lawrenceville police department": true,
  "lea county magistrate court in eunice": true,
  "lea county magistrate court in hobbs": true,
  "lea county magistrate court in jal": true,
  "lea county magistrate court in lovington": true,
  "lemon township police department": true,
  "lima parks department of police": true,
  "lima police department": true,
  "lincoln county magistrate court in carrizozo": true,
  "lincoln county magistrate court in ruidoso": true,
  "lisbon village police department": true,
  "lithopolis police department": true,
  "liverpool township police department": true,
  "logansport police department": true,
  "los alamos county magistrate court in los alamos": true,
  "loudonvillle police department": true,
  "louisiana department of public safety and corrections": true,
  "louisiana department of public safety & corrections": false,
  "lucas county corrections center": true,
  "lucas county criminal justice coordinating council": true,
  "luna county magistrate court in deming": true,
  "lyndhurst police department": true,
  "madison township police department (franklin)": true,
  "magnolia police department": true,
  "maine department of corrections": true,
  "malvern police department": true,
  "manchester police department": true,
  "maple heights police department": true,
  "marion county district court": true,
  "marion county prosecutor's office": true,
  "marion township police department": true,
  "marshall county district court": true,
  "marshalltown police department": true,
  "martins ferry police department": true,
  "martinsville police department": true,
  "maryland department of public safety and correctional services": true,
  "massachusetts court system": true,
  "massachusetts department of correction": false,
  "massachusetts parole board": true,
  "mayfield heights police department": true,
  "mayfield village police department": true,
  "mckinley county magistrate court in gallup": true,
  "mechanicsburg police department": true,
  "miami township police (clermont)": true,
  "miami university police department": true,
  "michigan department of corrections": true,
  "middleburg heights police department": true,
  "middletown police department": true,
  "mifflin police department": true,
  "mifflin township police department": true,
  "milford police department": true,
  "millersport police department": true,
  "minerva park police department": true,
  "minnesota department of corrections": true,
  "minster police department": true,
  "mississippi department of corrections": true,
  "missouri department of corrections": true,
  "monroe police department": true,
  "montana department of corrections": true,
  "mora county magistrate court in mora": true,
  "moreland hills police department": true,
  "morristown police department": true,
  "mount orab police department": true,
  "muskegon county prosecutor's office": true,
  "nebraska crime commission": true,
  "nebraska department of correctional services": false,
  "nelsonville police department": true,
  "nevada department of corrections": true,
  "new albany police department": true,
  "newark division of police": true,
  "new bremen police department": true,
  "newburgh heights police department": true,
  "new carlisle police department": true,
  "new hampshire department of corrections": false,
  "new jersey courts": true,
  "new jersey department of corrections": true,
  "new jersey state parole board": true,
  "new knoxville police department": true,
  "new madison police department": true,
  "new mexico administrative office of the courts": true,
  "new mexico corrections department": true,
  "new mexico sentencing commission": true,
  "new miami police department": true,
  "new richmond police department": true,
  "newtonsville police department": true,
  "new vienna police department": true,
  "new washington police department": true,
  "new waterford police department": true,
  "new york department of corrections and community supervision": true,
  "new york department of corrections & community supervision": true,
  "new york state department of corrections and community supervision": false,
  "ninth judicial district curry county": true,
  "ninth judicial district roosevelt county": true,
  "north carolina department of public safety": true,
  "north dakota department of corrections and rehabilitation": true,
  "north hampton police department": true,
  "north kingsville police department": true,
  "north olmsted police department": true,
  "north randall police department": true,
  "north royalton police department": true,
  "notre dame college campus police and safety": true,
  "oakwood village police department": true,
  "obetz police department": true,
  "ohio department of rehabilitation and correction": true,
  "ohio office of criminal justice services": true,
  "ohio university police department": true,
  "ohio veterans home police department": true,
  "oklahoma department of corrections": true,
  "olmsted falls police department": true,
  "olmsted township police department": true,
  "orange village police department": true,
  "oregon criminal justice commission": true,
  "oregon department of corrections": true,
  "oriana house": true,
  "orwell police department": true,
  "ostrander police department": true,
  "otero county magistrate court in alamogordo": true,
  "oxford police department": true,
  "oxford township police department": true,
  "palm beach county criminal justice commission": true,
  "parma heights police department": true,
  "parma police department": true,
  "peebles police department": true,
  "pennsylvania department of corrections": true,
  "pennsylvania parole board": true,
  "pepper pike police departmen": true,
  "perkins township police department": true,
  "perrysville police department": true,
  "perry township police department (allen)": true,
  "perry township police department (columbiana)": true,
  "perry township police department (franklin)": true,
  "pickerington police department": true,
  "pierce township police department": true,
  "platte county prosecutor's office": true,
  "polk county attorney's office": true,
  "polk county district court": true,
  "port william police department": true,
  "powell police department": true,
  "powhatan police department": true,
  "preservation parks of delaware county division of park police": true,
  "puerto rico department of corrections": false,
  "quay county magistrate court in tucumcari": true,
  "reynoldsburg police department": true,
  "rhode island department of corrections": true,
  "richland township police department": true,
  "richmond heights police department": true,
  "rio arriba county magistrate court in chama": true,
  "rio arriba county magistrate court in espanola": true,
  "ripley police department": true,
  "roaming shores police department": true,
  "rocky river police department": true,
  "rogers police department": true,
  "roosevelt county magistrate court in portales": true,
  "ross township police department": true,
  "russellville police department": true,
  "sabina police department": true,
  "saint paris police department": true,
  "salem city police department": true,
  "salem township police department (columbiana)": true,
  "sandoval county magistrate court in bernalillo": true,
  "sandoval county magistrate court in cuba": true,
  "san juan county magistrate court in aztec": true,
  "san juan county magistrate court in farmington": true,
  "san leandro police department": true,
  "san miguel county magistrate court in las vegas": true,
  "santa fe county magistrate court in santa fe": true,
  "sardinia police department": true,
  "seaman police department": true,
  "seattle police department": true,
  "second judicial district bernalillo county": true,
  "seven hills police department": true,
  "seven mile police department": true,
  "seventh judicial district catron county": true,
  "seventh judicial district sierra county": true,
  "seventh judicial district socorro county": true,
  "seventh judicial district torrance county": true,
  "shadyside police department": true,
  "shaker heights police department": true,
  "shawnee hills police department": true,
  "shawnee township police department": true,
  "sherrodsville police department": true,
  "sherwood village police department": true,
  "sierra county magistrate court in t or c": true,
  "sixth judicial district grant county": true,
  "sixth judicial district hidalgo county": true,
  "sixth judicial district luna county": true,
  "socorro county magistrate court in socorro": true,
  "solon police department": true,
  "south carolina department of corrections": true,
  "south carolina department of probation": true,
  "parole and pardon services": true,
  "south charleston police department": true,
  "south dakota department of corrections": true,
  "south dakota unified judicial system": true,
  "south euclid police department": true,
  "south vienna police department": true,
  "spencerville police department": true,
  "springfield police department": true,
  "state of connecticut judicial branch": true,
  "state of hawaii department of public safety": true,
  "st. clairsville police department": true,
  "st. clair township police department": true,
  "st. louis division of corrections": true,
  "st. marys police department": true,
  "story county attorney’s office": true,
  "story county district court": true,
  "strongsville police department": true,
  "sugar grove police department": true,
  "summitville police department": true,
  "sunbury police department": true,
  "taos county magistrate court in questa": true,
  "taos county magistrate court in taos": true,
  "tennessee department of correction": true,
  "tenth judicial district de baca county": true,
  "tenth judicial district harding county": true,
  "tenth judicial district quay county": true,
  "test agency ohio": true,
  "test agency ohio 2": true,
  "[test] law enforcement agency": true,
  "[test] prisons": true,
  "[test] supervision": true,
  "texas department of criminal justice": true,
  "the ohio state university - columbus police department": true,
  "the supreme court of indiana": true,
  "third judicial district dona ana county": true,
  "thirteenth judicial district cibola county": true,
  "thirteenth judicial district sandoval county": true,
  "thirteenth judicial district valencia county": true,
  "toledo municipal court": true,
  "toledo police department": true,
  "torrance county magistrate court in estancia": true,
  "torrance county magistrate court in moriarty": true,
  "tremont city police department": true,
  "trenton police department": true,
  "trimble village police department": true,
  "twelfth judicial district lincoln county": true,
  "twelfth judicial district otero county": true,
  "union county magistrate court in clayton": true,
  "union township police (clermont)": true,
  "uniopolis police department": true,
  "university circle police department": true,
  "university heights police department": true,
  "urbana police department": true,
  "utah department of corrections": true,
  "valencia county magistrate court in belen": true,
  "valencia county magistrate court in los lunas": true,
  "valley view police department": true,
  "valleyview police department (franklin)": true,
  "vera institute of justice": true,
  "vermont department of corrections": true,
  "versailles police department": true,
  "village of crestline police department": true,
  "village of leetonia police department": true,
  "village of linndale police department": true,
  "village of milan police department": true,
  "village of moscow police department": true,
  "village of new rome police department": true,
  "village of ney police department": true,
  "village of owensville police department": true,
  "village of salineville police department": true,
  "village of union city police department": true,
  "village of williamsburg police department": true,
  "virginia department of corrections": true,
  "walton hills police department": true,
  "wapakoneta police department": true,
  "warrensville heights police department": true,
  "washington court house police department": true,
  "washington department of corrections": true,
  "washington state department of corrections": true,
  "washington township police department (franklin)": true,
  "washingtonville police department": true,
  "waynesfield police department": true,
  "wayne township police department": true,
  "wellsville police department": true,
  "west chester police department": true,
  "westerville police department": true,
  "west lafayette police department": true,
  "westlake police department": true,
  "west union police department": true,
  "west virginia division of corrections and rehabilitation": true,
  "whitehall division of police": true,
  "wilmington police department": true,
  "winchester police department": true,
  "wisconsin department of corrections": false,
  "wisconsin department of justice": true,
  "wittenberg university police division": true,
  "woodmere village police department": true,
  "worthington police department": true,
  "wyoming department of corrections": true,
  "yavapai county district attorney": true,
};

export const isDenyListed = ({ name }: UserAgency): boolean | undefined => {
  const lowercaseName = name.toLocaleLowerCase();
  return DENY_LIST[lowercaseName];
};

// DELETE after verifying these agencies are properly copied over to new deny list
// export const ALLOW_LIST: Record<string, boolean> = {
//   "Puerto Rico Department of Corrections": true,
//   "Louisiana Department Of Public Safety & Corrections": true,
//   "Nebraska Department Of Correctional Services": true,
//   "New Hampshire Department Of Corrections": true,
//   "Massachusetts Department of Correction": true,
//   "New York State Department of Corrections And Community Supervision": true,
//   "Wisconsin Department of Corrections": true,
//   "Johnson County Prosecutor's Office": true,
// };
