// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2023 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { UserAgency } from "@justice-counts/common/types";

/**
 * The DENY_LIST is our way of controlling whether or not an agency's dashboard is live and visible to the public.
 *
 *
 * Agencies on this list WILL NOT have their dashboard live and visible
 * Agencies NOT on this list WILL have their dashboard live and visible
 *
 * Note:
 *   - the DENY_LIST is temporary until we implement a backend solution
 *   - this list contains only a snapshot of agencies at the time the switch from ALLOW_LIST to DENY_LIST
 *     took place
 *   - all newly created agencies moving forward will default to having a live and visible dashboard
 *   - the purpose of this hardcoded list is to keep the existing agencies' dashboards hidden until they explicitly decide to
 *     go live with their dashboard
 */
export const DENY_LIST = new Set([
  "22nd judicial circuit court",
  "aberdeen police department",
  "adams county sheriff's office",
  "administrative office of the illinois courts",
  "alabama department of corrections",
  "alaska department of corrections",
  "albany village police dept",
  "allen county sheriff's office",
  "amanda police department",
  "amelia police department",
  "american township police department",
  "amesville village police department",
  "andover police department",
  "ansonia police department",
  "arcanum police department",
  "arizona corrections [test]",
  "arizona court [test]",
  "arizona criminal justice commission",
  "arizona department of corrections",
  "rehabilitation & reentry",
  "arizona supervision [test]",
  "arizona supreme court",
  "adult probation services division",
  "arkansas department of correction",
  "arkansas division of community correction",
  "arkansas division of correction",
  "ashland county sheriff's office",
  "ashland police department",
  "ashley police department",
  "ashtabula county sheriff's office",
  "ashtabula police department",
  "athens county sheriff's office",
  "athens police department",
  "auglaize county sheriff's office",
  "baldwin wallace university safety and security office",
  "baltimore police department",
  "barnesville police department",
  "batavia police department",
  "bath township police department (allen)",
  "bay view police department",
  "bay village police department",
  "beachwood police department",
  "bedford heights police department",
  "bedford police department",
  "bellaire police department",
  "belmont county sheriff's office",
  "belmont police department",
  "bentleyville police department",
  "berea police department",
  "berlin heights police department",
  "bernalillo county metropolitan court",
  "bethel police department",
  "bethesda police department",
  "bexley police department",
  "blanchester police department",
  "blendon township police department",
  "bluffton police department",
  "bratenahl police department",
  "brecksville police department",
  "brice police department",
  "bridgeport police department",
  "broadview heights police department",
  "brooklyn heights police department",
  "brooklyn police department",
  "brook park police department",
  "brown county sheriff's office",
  "buchtel police department",
  "buckland police departmet",
  "bucyrus police department",
  "butler county metroparks police",
  "butler county sheriff's office",
  "cairo police department",
  "california department of corrections and rehabilitation",
  "carroll county sheriff's office",
  "carroll police department",
  "carrollton police department",
  "cass county court and pretrial services",
  "cass county sheriff’s department",
  "cass/pulaski community corrections",
  "castalia police department",
  "catawba police department",
  "catron county magistrate court in quemado",
  "catron county magistrate court in reserve",
  "cedar point police department",
  "center township police department",
  "chagrin falls police department",
  "champaign county sheriff's office",
  "chauncey police department",
  "chaves county magistrate court in roswell",
  "chief probation officers of california",
  "cibola county magistrae court in grants",
  "city of sandusky police department",
  "city of upper arlington police division",
  "city of vermilion police department",
  "clackamas county jail",
  "clark county park district police",
  "clark county sheriff's office",
  "clermont county sheriff's office",
  "cleveland heights police department",
  "cleveland lakefront state parks",
  "cleveland metroparks ranger police department",
  "cleveland municipal court probation department",
  "cleveland police department",
  "cleveland state university police department",
  "clinton county sheriff's office",
  "clinton township police department",
  "colfax county magistrate court in raton",
  "colfax county magistrate court in springer",
  "colorado department of corrections",
  "colorado department of public safety",
  "colorado judicial branch",
  "columbiana county sheriff's office",
  "columbiana police department",
  "columbus city attorney’s office",
  "columbus police department",
  "conneaut police department",
  "connecticut department of correction",
  "connecticut office of policy and management",
  "coolville marshal police department",
  "coshocton county sheriff's office",
  "coshocton police department",
  "crawford county sheriff's office",
  "cridersville police department",
  "curry county magistrate court in clovis",
  "cuyahoga community college campus police and security services",
  "cuyahoga county sheriff's office",
  "cuyahoga heights police department",
  "cuyahoga metropolitan housing authority",
  "darbydale police department",
  "darke county sheriff's office",
  "debaca county magistrate court in fort sumner",
  "defiance county sheriff's office",
  "defiance police department",
  "delaware county sheriff's office",
  "delaware department of correction",
  "delaware police department",
  "[delete] georgia judicial council and administrative office of the courts",
  "[delete] illinois criminal justice information authority (icja)",
  "dellroy marshal police department",
  "delphos police department",
  "[deprecated] north carolina department of public safety",
  "district of columbia department of corrections",
  "division of criminal and juvenile justice planning of the iowa department of human rights",
  "dona ana county magistrate court in anthony",
  "dona ana county magistrate court in hatch",
  "dona ana county magistrate court in las cruces",
  "donnelsville police department",
  "douglas county district attorney's office",
  "dublin police department",
  "east cleveland police department",
  "eastern ohio corrections center",
  "east liverpool police department",
  "east palestine police department",
  "eddy county magistrate court in artesia",
  "eddy county magistrate court in carlsbad",
  "eighth judicial district colfax county",
  "eighth judicial district taos county",
  "eighth judicial district union county",
  "eleventh judicial district mckinley county",
  "eleventh judicial district san juan county",
  "elida police department",
  "enon police department",
  "erie county sheriff's office",
  "erie metroparks police department and safety",
  "euclid police department",
  "fairfield county sheriff's office",
  "fairfield police department",
  "fairfield township police department",
  "fairview park police department",
  "fayette county sheriff's office",
  "fayetteville police department",
  "felicity police department",
  "fifth judicial district chaves county",
  "fifth judicial district eddy county",
  "fifth judicial district lea county",
  "first judicial district los alamos county",
  "first judicial district rio arriba county",
  "first judicial district santa fe county",
  "florida commission on offender review",
  "florida department of corrections",
  "flushing police department",
  "fort shawnee police department",
  "fourth judicial district guadalupe county",
  "fourth judicial district mora county",
  "fourth judicial district san miguel county",
  "franklin county common pleas court",
  "franklin county community based correctional facility",
  "franklin county metro park rangers",
  "franklin county municipal court",
  "franklin county prosecutor’s office",
  "franklin county public defender’s office",
  "franklin county sheriff's office",
  "franklin township police department",
  "gahanna division of police",
  "galena police department",
  "galion police department",
  "garfield heights police department",
  "gates mills police department",
  "geneva-on-the-lake police department",
  "geneva police department",
  "genoa township police department",
  "georgetown police department",
  "georgia department of community supervision",
  "georgia department of corrections",
  "georgia judicial council and administrative office of the courts",
  "german township police department (clark)",
  "glenwillow village police department",
  "glouster police department",
  "goshen township police (clermont)",
  "grandview heights division of police",
  "grant county magistrate court in bayard",
  "grant county magistrate court in silver city",
  "greater cleveland regional transit authority police department",
  "greenville police department",
  "grove city division of police",
  "groveport police department",
  "guadalupe county magistrate court in santa rosa",
  "hamersville police department",
  "hamilton police department",
  "hamilton township police department (franklin)",
  "hanoverton police department",
  "harding county magistrate court in roy",
  "harrisburg police department",
  "harrod police department",
  "hawaii department of public safety",
  "hawaii paroling authority",
  "hawaii state judiciary",
  "hayesville police department",
  "hicksville police department",
  "hidalgo county magistrate court in lordsburg",
  "higginsport police department",
  "highland heights police department",
  "highland hills police department",
  "hilliard division of police",
  "hocking college police department",
  "howard county community supervision",
  "howard county superior court",
  "hunting valley police department",
  "huron police association",
  "idaho criminal justice commission",
  "idaho department of correction",
  "illinois criminal justice information authority (icja)",
  "illinois department of corrections",
  "independence police department",
  "indiana department of correction",
  "indiana public defender commission",
  "iowa department of corrections",
  "iowa state university police department",
  "jacksonville police department",
  "jefferson police department",
  "jeromesville police department",
  "johnny appleseed park rangers",
  "johnson county district court",
  "kansas department of corrections",
  "kelleys island police department",
  "kentucky department of corrections",
  "lake waynoka rangers",
  "lakewood police department",
  "lancaster police department",
  "law offices of the public defender",
  "lawrenceville police department",
  "lea county magistrate court in eunice",
  "lea county magistrate court in hobbs",
  "lea county magistrate court in jal",
  "lea county magistrate court in lovington",
  "lemon township police department",
  "lima parks department of police",
  "lima police department",
  "lincoln county magistrate court in carrizozo",
  "lincoln county magistrate court in ruidoso",
  "lisbon village police department",
  "lithopolis police department",
  "liverpool township police department",
  "logansport police department",
  "los alamos county magistrate court in los alamos",
  "loudonvillle police department",
  "louisiana department of public safety and corrections",
  "lucas county corrections center",
  "lucas county criminal justice coordinating council",
  "luna county magistrate court in deming",
  "lyndhurst police department",
  "madison township police department (franklin)",
  "magnolia police department",
  "maine department of corrections",
  "malvern police department",
  "manchester police department",
  "maple heights police department",
  "marion county district court",
  "marion county prosecutor's office",
  "marion township police department",
  "marshall county district court",
  "marshalltown police department",
  "martins ferry police department",
  "martinsville police department",
  "maryland department of public safety and correctional services",
  "massachusetts court system",
  "massachusetts parole board",
  "mayfield heights police department",
  "mayfield village police department",
  "mckinley county magistrate court in gallup",
  "mechanicsburg police department",
  "miami township police (clermont)",
  "miami university police department",
  "michigan department of corrections",
  "middleburg heights police department",
  "middletown police department",
  "mifflin police department",
  "mifflin township police department",
  "milford police department",
  "millersport police department",
  "minerva park police department",
  "minnesota department of corrections",
  "minster police department",
  "mississippi department of corrections",
  "missouri department of corrections",
  "monroe police department",
  "montana department of corrections",
  "mora county magistrate court in mora",
  "moreland hills police department",
  "morristown police department",
  "mount orab police department",
  "muskegon county prosecutor's office",
  "nebraska crime commission",
  "nelsonville police department",
  "nevada department of corrections",
  "new albany police department",
  "newark division of police",
  "new bremen police department",
  "newburgh heights police department",
  "new carlisle police department",
  "new jersey courts",
  "new jersey department of corrections",
  "new jersey state parole board",
  "new knoxville police department",
  "new madison police department",
  "new mexico administrative office of the courts",
  "new mexico corrections department",
  "new mexico sentencing commission",
  "new miami police department",
  "new richmond police department",
  "newtonsville police department",
  "new vienna police department",
  "new washington police department",
  "new waterford police department",
  "new york department of corrections and community supervision",
  "new york department of corrections & community supervision",
  "ninth judicial district curry county",
  "ninth judicial district roosevelt county",
  "north carolina department of public safety",
  "north dakota department of corrections and rehabilitation",
  "north hampton police department",
  "north kingsville police department",
  "north olmsted police department",
  "north randall police department",
  "north royalton police department",
  "notre dame college campus police and safety",
  "oakwood village police department",
  "obetz police department",
  "ohio department of rehabilitation and correction",
  "ohio office of criminal justice services",
  "ohio university police department",
  "ohio veterans home police department",
  "oklahoma department of corrections",
  "olmsted falls police department",
  "olmsted township police department",
  "orange village police department",
  "oregon criminal justice commission",
  "oregon department of corrections",
  "oriana house",
  "orwell police department",
  "ostrander police department",
  "otero county magistrate court in alamogordo",
  "oxford police department",
  "oxford township police department",
  "palm beach county criminal justice commission",
  "parma heights police department",
  "parma police department",
  "peebles police department",
  "pennsylvania department of corrections",
  "pennsylvania parole board",
  "pepper pike police departmen",
  "perkins township police department",
  "perrysville police department",
  "perry township police department (allen)",
  "perry township police department (columbiana)",
  "perry township police department (franklin)",
  "pickerington police department",
  "pierce township police department",
  "platte county prosecutor's office",
  "polk county attorney's office",
  "polk county district court",
  "port william police department",
  "powell police department",
  "powhatan police department",
  "preservation parks of delaware county division of park police",
  "quay county magistrate court in tucumcari",
  "reynoldsburg police department",
  "rhode island department of corrections",
  "richland township police department",
  "richmond heights police department",
  "rio arriba county magistrate court in chama",
  "rio arriba county magistrate court in espanola",
  "ripley police department",
  "roaming shores police department",
  "rocky river police department",
  "rogers police department",
  "roosevelt county magistrate court in portales",
  "ross township police department",
  "russellville police department",
  "sabina police department",
  "saint paris police department",
  "salem city police department",
  "salem township police department (columbiana)",
  "sandoval county magistrate court in bernalillo",
  "sandoval county magistrate court in cuba",
  "san juan county magistrate court in aztec",
  "san juan county magistrate court in farmington",
  "san leandro police department",
  "san miguel county magistrate court in las vegas",
  "santa fe county magistrate court in santa fe",
  "sardinia police department",
  "seaman police department",
  "seattle police department",
  "second judicial district bernalillo county",
  "seven hills police department",
  "seven mile police department",
  "seventh judicial district catron county",
  "seventh judicial district sierra county",
  "seventh judicial district socorro county",
  "seventh judicial district torrance county",
  "shadyside police department",
  "shaker heights police department",
  "shawnee hills police department",
  "shawnee township police department",
  "sherrodsville police department",
  "sherwood village police department",
  "sierra county magistrate court in t or c",
  "sixth judicial district grant county",
  "sixth judicial district hidalgo county",
  "sixth judicial district luna county",
  "socorro county magistrate court in socorro",
  "solon police department",
  "south carolina department of corrections",
  "south carolina department of probation",
  "parole and pardon services",
  "south charleston police department",
  "south dakota department of corrections",
  "south dakota unified judicial system",
  "south euclid police department",
  "south vienna police department",
  "spencerville police department",
  "springfield police department",
  "state of connecticut judicial branch",
  "state of hawaii department of public safety",
  "st. clairsville police department",
  "st. clair township police department",
  "st. louis division of corrections",
  "st. marys police department",
  "story county attorney’s office",
  "story county district court",
  "strongsville police department",
  "sugar grove police department",
  "summitville police department",
  "sunbury police department",
  "taos county magistrate court in questa",
  "taos county magistrate court in taos",
  "tennessee department of correction",
  "tenth judicial district de baca county",
  "tenth judicial district harding county",
  "tenth judicial district quay county",
  "test agency ohio",
  "test agency ohio 2",
  "[test] law enforcement agency",
  "[test] prisons",
  "[test] supervision",
  "texas department of criminal justice",
  "the ohio state university - columbus police department",
  "the supreme court of indiana",
  "third judicial district dona ana county",
  "thirteenth judicial district cibola county",
  "thirteenth judicial district sandoval county",
  "thirteenth judicial district valencia county",
  "toledo municipal court",
  "toledo police department",
  "torrance county magistrate court in estancia",
  "torrance county magistrate court in moriarty",
  "tremont city police department",
  "trenton police department",
  "trimble village police department",
  "twelfth judicial district lincoln county",
  "twelfth judicial district otero county",
  "union county magistrate court in clayton",
  "union township police (clermont)",
  "uniopolis police department",
  "university circle police department",
  "university heights police department",
  "urbana police department",
  "utah department of corrections",
  "valencia county magistrate court in belen",
  "valencia county magistrate court in los lunas",
  "valley view police department",
  "valleyview police department (franklin)",
  "vera institute of justice",
  "vermont department of corrections",
  "versailles police department",
  "village of crestline police department",
  "village of leetonia police department",
  "village of linndale police department",
  "village of milan police department",
  "village of moscow police department",
  "village of new rome police department",
  "village of ney police department",
  "village of owensville police department",
  "village of salineville police department",
  "village of union city police department",
  "village of williamsburg police department",
  "virginia department of corrections",
  "walton hills police department",
  "wapakoneta police department",
  "warrensville heights police department",
  "washington court house police department",
  "washington department of corrections",
  "washington state department of corrections",
  "washington township police department (franklin)",
  "washingtonville police department",
  "waynesfield police department",
  "wayne township police department",
  "wellsville police department",
  "west chester police department",
  "westerville police department",
  "west lafayette police department",
  "westlake police department",
  "west union police department",
  "west virginia division of corrections and rehabilitation",
  "whitehall division of police",
  "wilmington police department",
  "winchester police department",
  "wisconsin department of justice",
  "wittenberg university police division",
  "woodmere village police department",
  "worthington police department",
  "wyoming department of corrections",
  "yavapai county district attorney",
]);

export const isDenyListed = ({ name }: UserAgency): boolean | undefined => {
  const lowercaseName = name.toLocaleLowerCase();
  return DENY_LIST.has(lowercaseName);
};
