// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2023 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import { Badge } from "@justice-counts/common/components/Badge";
import { Button } from "@justice-counts/common/components/Button";
import { HeaderBar } from "@justice-counts/common/components/HeaderBar";
import { Modal } from "@justice-counts/common/components/Modal";
import { TabbedBar } from "@justice-counts/common/components/TabbedBar";
import { observer } from "mobx-react-lite";
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import { Environment, EnvironmentType, Setting, SettingType } from ".";
import * as Styled from "./AdminPanel.styles";
import { AgencyProvisioning } from "./AgencyProvisioning";
import { UserProvisioning } from "./UserProvisioning";
// import { useStore } from "../../stores";

export const AdminPanel = observer(() => {
  // const { api } = useStore();
  const navigate = useNavigate();

  const [currentEnvironment, setCurrentEnvironment] =
    useState<EnvironmentType>();
  const [currentSettingType, setCurrentSettingType] = useState<SettingType>(
    Setting.USERS
  );

  const [users, setUsers] = useState<any[]>([]);
  const [agencies, setAgencies] = useState<any[]>([]);
  const [systems, setSystems] = useState<any[]>([]);

  const resetEnvironmentSettingType = () => {
    setCurrentEnvironment(undefined);
    setCurrentSettingType(Setting.USERS);
  };

  useEffect(() => {
    // Mock Fetch
    setUsers(usersResponse.users);
    setAgencies(agenciesResponse.agencies);
    setSystems(agenciesResponse.systems);
  }, []);

  const settingOptions = [
    {
      key: "users",
      label: "Users",
      onClick: () => setCurrentSettingType(Setting.USERS),
      selected: currentSettingType === Setting.USERS,
    },
    {
      key: "agencies",
      label: "Agencies",
      onClick: () => setCurrentSettingType(Setting.AGENCIES),
      selected: currentSettingType === Setting.AGENCIES,
    },
  ];

  return (
    <Styled.AdminPanelContainer>
      <HeaderBar onLogoClick={() => navigate("/admin")} hasBottomBorder>
        <Styled.HeaderEnvironmentDisplay>
          {currentEnvironment}
        </Styled.HeaderEnvironmentDisplay>
        Admin Panel
      </HeaderBar>

      {/* Interstitial: Staging or Production? */}
      {!currentEnvironment && (
        <Styled.AdminPanelEnvironmentInterstitial>
          <Styled.InterstitialTitle>
            Which environment would you like to update?
          </Styled.InterstitialTitle>
          <Styled.EnvironmentOptionsWrapper>
            <Styled.EnvironmentOption
              onClick={() => setCurrentEnvironment(Environment.STAGING)}
            >
              Staging
            </Styled.EnvironmentOption>
            <Styled.EnvironmentOption
              onClick={() => setCurrentEnvironment(Environment.PRODUCTION)}
            >
              Production
            </Styled.EnvironmentOption>
          </Styled.EnvironmentOptionsWrapper>
        </Styled.AdminPanelEnvironmentInterstitial>
      )}

      {currentEnvironment && (
        <Styled.AdminPanelWrapper>
          <Styled.EnvironmentSwitchWrapper>
            <Styled.EnvironmentSwitchButton
              onClick={resetEnvironmentSettingType}
            >
              &larr; Switch Environments
            </Styled.EnvironmentSwitchButton>
          </Styled.EnvironmentSwitchWrapper>
          <TabbedBar options={settingOptions} />

          {/* Staging */}
          {currentEnvironment === Environment.STAGING && (
            <Styled.SettingsContainer>
              {currentSettingType === Setting.USERS && (
                <UserProvisioning users={users} />
              )}
              {currentSettingType === Setting.AGENCIES && (
                <AgencyProvisioning agencies={agencies} />
              )}
            </Styled.SettingsContainer>
          )}

          {/* Production */}
          {currentEnvironment === Environment.PRODUCTION && (
            <>
              {currentSettingType === Setting.USERS && <>User Settings</>}
              {currentSettingType === Setting.AGENCIES && <>Agency Settings</>}
            </>
          )}
        </Styled.AdminPanelWrapper>
      )}
    </Styled.AdminPanelContainer>
  );
});

const agenciesResponse = {
  agencies: [
    {
      fips_county_code: "us_or_clackamas",
      id: 161,
      is_superagency: null,
      name: "Clackamas County Jail",
      settings: [],
      state: "Oregon",
      state_code: "us_or",
      super_agency_id: null,
      systems: ["JAILS"],
      team: [
        {
          auth0_user_id: "auth0|62828175a5229e006fa2290b",
          email: "lili@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Lili",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6283e92b31dd3e006fdaffda",
          email: "mahmoud@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Mahmoud",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62853dff791d69006f50f19d",
          email: "nichelle@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Nichelle Hall",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62ac97ba2d88a681ff88ddbd",
          email: "mherman@csg.org",
          invitation_status: "ACCEPTED",
          name: "Matt Herman",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|629628319f55cf006ad941c3",
          email: "juan@recidiviz.org",
          invitation_status: null,
          name: "Juan",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62ac980a5f819dbd6e708c22",
          email: "kmosehauer@csg.org",
          invitation_status: "ACCEPTED",
          name: "Katie Mosehauer",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|62ac97e215f8eea7bbda2246",
          email: "slee@csg.org",
          invitation_status: "ACCEPTED",
          name: "Sarah Lee",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595110469762a022f20f7c",
          email: "svillanueva@csg.org",
          invitation_status: "ACCEPTED",
          name: "Stephanie Villanueva",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595172bf70f1182ebdd776",
          email: "mroman-scott@csg.org",
          invitation_status: "ACCEPTED",
          name: "Madelyn Roman-Scott",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6363e4afd714312aa565ea0b",
          email: "michelle@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Michelle Orden",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|636be9f047180f0a6d76db0b",
          email: "snehaladke@gmail.com",
          invitation_status: null,
          name: "snehaladke@gmail.com",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6359518e6f2627668548c82c",
          email: "vvenkatesha@csg.org",
          invitation_status: null,
          name: "Vibha Venkatesha",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595288bf70f1182ebdd8bb",
          email: "bshelor@csg.org",
          invitation_status: null,
          name: "Ben Shelor",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595249f86b19285f1c58d0",
          email: "abrunson@csg.org",
          invitation_status: "ACCEPTED",
          name: "Antoine Brunson",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63c0250400d37d4af86c12bb",
          email: "ivan.k@inobright.com",
          invitation_status: "ACCEPTED",
          name: "Langa",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63cedc26741e7f0b79527eb9",
          email: "kalbis@csg.org",
          invitation_status: null,
          name: "Katy Albis",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc15f811dda05614664a9d",
          email: "jsaunders@csg.org",
          invitation_status: null,
          name: "Jessica Saunders",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc15dcbcd90c937266c63e",
          email: "jmallett@csg.org",
          invitation_status: null,
          name: "Joshua Mallett",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc15b2b124da2e44be5b95",
          email: "snystrom@csg.org",
          invitation_status: null,
          name: "Sofia Nystrom",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc1d562fb7a2c283986107",
          email: "lvanderlugt@csg.org",
          invitation_status: null,
          name: "Laura",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|6359526cf76fc1e9e40a4e0c",
          email: "kdonald@csg.org",
          invitation_status: null,
          name: "Keosha Donald",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|64259f9e1f0382fcfa049caa",
          email: "jessica@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Jessica",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6425d8bf1f0382fcfa04e337",
          email: "forrest@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Forrest Kim",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|645d49c88b442229f4a20514",
          email: "alfonso@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Alfonso Gober",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6499acaf1f09bbe2c36a4a95",
          email: "evan@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Evan Green-Lowe",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|64baea172ae20c51edd279ce",
          email: "abyrum@csg.org",
          invitation_status: "ACCEPTED",
          name: "Andrew Byrum",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|64da4d36a6ef7a07860611ee",
          email: "adaniels@csg.org",
          invitation_status: null,
          name: "Ana Daniels",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|64daa0d4ce722e32f3c311b2",
          email: "forrestkim@recidiviz.org",
          invitation_status: "PENDING",
          name: "Forrest Kim",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|64fb4db5b047c9ac734e6f53",
          email: "darren@hyperscalemarketing.com",
          invitation_status: null,
          name: "Darren Utt",
          role: "READ_ONLY",
        },
      ],
    },
    {
      fips_county_code: "us_mi_muskegon",
      id: 162,
      is_superagency: null,
      name: "Muskegon County Prosecutor's Office",
      settings: [],
      state: "Michigan",
      state_code: "us_mi",
      super_agency_id: null,
      systems: ["PROSECUTION"],
      team: [
        {
          auth0_user_id: "auth0|62828175a5229e006fa2290b",
          email: "lili@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Lili",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62843394cebefb00683be31d",
          email: "terry@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Terry T",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62869e52843fe9006fa81e25",
          email: "humphrey@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Humphrey Obuobi",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6283e92b31dd3e006fdaffda",
          email: "mahmoud@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Mahmoud",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62853dff791d69006f50f19d",
          email: "nichelle@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Nichelle Hall",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62ac97ba2d88a681ff88ddbd",
          email: "mherman@csg.org",
          invitation_status: "ACCEPTED",
          name: "Matt Herman",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|629628319f55cf006ad941c3",
          email: "juan@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Juan",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|62ac980a5f819dbd6e708c22",
          email: "kmosehauer@csg.org",
          invitation_status: "ACCEPTED",
          name: "Katie Mosehauer",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|634d73e51d95833aa7472efb",
          email: "jamie@doc1.wa.gov",
          invitation_status: null,
          name: "jamie",
          role: null,
        },
        {
          auth0_user_id: "auth0|62ac97e215f8eea7bbda2246",
          email: "slee@csg.org",
          invitation_status: "ACCEPTED",
          name: "Sarah Lee",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595110469762a022f20f7c",
          email: "svillanueva@csg.org",
          invitation_status: "ACCEPTED",
          name: "Stephanie Villanueva",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595172bf70f1182ebdd776",
          email: "mroman-scott@csg.org",
          invitation_status: "ACCEPTED",
          name: "Madelyn Roman-Scott",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6363e4afd714312aa565ea0b",
          email: "michelle@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Michelle Orden",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|636be9f047180f0a6d76db0b",
          email: "snehaladke@gmail.com",
          invitation_status: null,
          name: "snehaladke@gmail.com",
          role: null,
        },
        {
          auth0_user_id: "auth0|6359518e6f2627668548c82c",
          email: "vvenkatesha@csg.org",
          invitation_status: "ACCEPTED",
          name: "Vibha Venkatesha",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595288bf70f1182ebdd8bb",
          email: "bshelor@csg.org",
          invitation_status: null,
          name: "Ben Shelor",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63595249f86b19285f1c58d0",
          email: "abrunson@csg.org",
          invitation_status: "ACCEPTED",
          name: "Antoine Brunson",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63c0250400d37d4af86c12bb",
          email: "ivan.k@inobright.com",
          invitation_status: "ACCEPTED",
          name: "Langa",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|637412a4f7c56cd29d591538",
          email: "kristen.yoonjo@gmail.com",
          invitation_status: "ACCEPTED",
          name: "kristen.yoonjo@gmail.com",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63cedc26741e7f0b79527eb9",
          email: "kalbis@csg.org",
          invitation_status: "ACCEPTED",
          name: "Katy Albis",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc15f811dda05614664a9d",
          email: "jsaunders@csg.org",
          invitation_status: null,
          name: "Jessica Saunders",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc15dcbcd90c937266c63e",
          email: "jmallett@csg.org",
          invitation_status: null,
          name: "Joshua Mallett",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc15b2b124da2e44be5b95",
          email: "snystrom@csg.org",
          invitation_status: null,
          name: "Sofia Nystrom",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|63dc1d562fb7a2c283986107",
          email: "lvanderlugt@csg.org",
          invitation_status: null,
          name: "Laura",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|6359526cf76fc1e9e40a4e0c",
          email: "kdonald@csg.org",
          invitation_status: null,
          name: "Keosha Donald",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|64259f9e1f0382fcfa049caa",
          email: "jessica@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Jessica",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|6425d8bf1f0382fcfa04e337",
          email: "forrest@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Forrest Kim",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|645d49c88b442229f4a20514",
          email: "alfonso@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Alfonso Gober",
          role: null,
        },
        {
          auth0_user_id: "auth0|6499acaf1f09bbe2c36a4a95",
          email: "evan@recidiviz.org",
          invitation_status: "ACCEPTED",
          name: "Evan Green-Lowe",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|64baea172ae20c51edd279ce",
          email: "abyrum@csg.org",
          invitation_status: "ACCEPTED",
          name: "Andrew Byrum",
          role: "JUSTICE_COUNTS_ADMIN",
        },
        {
          auth0_user_id: "auth0|64da4d36a6ef7a07860611ee",
          email: "adaniels@csg.org",
          invitation_status: null,
          name: "Ana Daniels",
          role: "AGENCY_ADMIN",
        },
        {
          auth0_user_id: "auth0|64fb4db5b047c9ac734e6f53",
          email: "darren@hyperscalemarketing.com",
          invitation_status: null,
          name: "Darren Utt",
          role: "READ_ONLY",
        },
      ],
    },
  ],
  systems: [
    "SUPERAGENCY",
    "LAW_ENFORCEMENT",
    "PROSECUTION",
    "DEFENSE",
    "COURTS_AND_PRETRIAL",
    "JAILS",
    "PRISONS",
    "SUPERVISION",
    "PAROLE",
    "PROBATION",
    "PRETRIAL_SUPERVISION",
    "OTHER_SUPERVISION",
    "CORRECTIONS",
    "COURT_PROCESSES",
    "COMMUNITY_SUPERVISION_AND_REENTRY",
    "POST_RELEASE",
    "DUAL_SUPERVISION",
  ],
};

const usersResponse = {
  users: [
    {
      agencies: [
        {
          fips_county_code: null,
          id: 196,
          is_superagency: false,
          name: "Department of Lili",
          settings: [],
          state: "New York",
          state_code: "us_ny",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION", "PAROLE", "PROBATION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 177,
          is_superagency: null,
          name: "Prosecution [DEMO]",
          settings: [],
          state: "Illinois",
          state_code: "us_il",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 152,
          is_superagency: null,
          name: "Prisons",
          settings: [],
          state: "New York",
          state_code: "us_ny",
          super_agency_id: null,
          systems: ["PRISONS"],
          team: [],
        },
        {
          fips_county_code: "us_or_clackamas",
          id: 161,
          is_superagency: null,
          name: "Clackamas County Jail",
          settings: [],
          state: "Oregon",
          state_code: "us_or",
          super_agency_id: null,
          systems: ["JAILS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 291,
          is_superagency: true,
          name: "LE Superagency [Test]",
          settings: [],
          state: "Alaska",
          state_code: "us_ak",
          super_agency_id: null,
          systems: ["SUPERAGENCY", "LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 180,
          is_superagency: null,
          name: "Supervision [DEMO]",
          settings: [],
          state: "Colorado",
          state_code: "us_co",
          super_agency_id: null,
          systems: ["SUPERVISION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 184,
          is_superagency: null,
          name: "Iowa Department of Corrections (STAGING)",
          settings: [],
          state: "Iowa",
          state_code: "us_ia",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 204,
          is_superagency: false,
          name: "Department of Corrections",
          settings: [],
          state: "Iowa",
          state_code: "us_ia",
          super_agency_id: null,
          systems: ["PRISONS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 147,
          is_superagency: null,
          name: "Law Enforcement",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: "us_ny_new_york",
          id: 148,
          is_superagency: null,
          name: "Defense",
          settings: [],
          state: "New York",
          state_code: "us_ny",
          super_agency_id: null,
          systems: ["DEFENSE"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 171,
          is_superagency: null,
          name: "Ames Police Department",
          settings: [],
          state: "Iowa",
          state_code: "us_ia",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 172,
          is_superagency: null,
          name: "Franklin County Public Defender’s Office",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: null,
          systems: ["DEFENSE"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 173,
          is_superagency: null,
          name: "Franklin County Municipal Court",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: null,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 149,
          is_superagency: null,
          name: "Prosecution",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 150,
          is_superagency: null,
          name: "Courts",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 151,
          is_superagency: null,
          name: "Jails",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["JAILS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 153,
          is_superagency: null,
          name: "Supervision",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: [
            "SUPERVISION",
            "PROBATION",
            "PRETRIAL_SUPERVISION",
            "OTHER_SUPERVISION",
          ],
          team: [],
        },
        {
          fips_county_code: "us_mi_muskegon",
          id: 162,
          is_superagency: null,
          name: "Muskegon County Prosecutor's Office",
          settings: [],
          state: "Michigan",
          state_code: "us_mi",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: "us_ga_douglas",
          id: 163,
          is_superagency: null,
          name: "Douglas County District Attorney's Office",
          settings: [],
          state: "Georgia",
          state_code: "us_ga",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 164,
          is_superagency: null,
          name: "North Carolina Department of Public Safety (NCDPS)",
          settings: [],
          state: "North Carolina",
          state_code: "us_nc",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION", "PROBATION"],
          team: [],
        },
        {
          fips_county_code: "us_ca_alameda",
          id: 165,
          is_superagency: null,
          name: "San Leandro Police Department",
          settings: [],
          state: "California",
          state_code: "us_ca",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 174,
          is_superagency: null,
          name: "Law Enforcement [DEMO]",
          settings: [],
          state: "California",
          state_code: "us_ca",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 179,
          is_superagency: null,
          name: "Prisons [DEMO]",
          settings: [],
          state: "Nevada",
          state_code: "us_nv",
          super_agency_id: null,
          systems: ["PRISONS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 185,
          is_superagency: true,
          name: "Ohio Office of Criminal Justice Services",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: null,
          systems: ["SUPERAGENCY", "LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 186,
          is_superagency: null,
          name: "Columbus Police Department",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: 185,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 190,
          is_superagency: null,
          name: "Newark Division of Police",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: 185,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: "us_ct_tolland",
          id: 167,
          is_superagency: null,
          name: "Supervision II",
          settings: [],
          state: "Connecticut",
          state_code: "us_ct",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION"],
          team: [],
        },
        {
          fips_county_code: "us_ar_baxter",
          id: 168,
          is_superagency: null,
          name: "Supervision III",
          settings: [],
          state: "Arkansas",
          state_code: "us_ar",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION", "PAROLE", "PROBATION"],
          team: [],
        },
        {
          fips_county_code: "us_az_yavapai",
          id: 166,
          is_superagency: null,
          name: "Yavapai County District Attorney's Office",
          settings: [],
          state: "Arizona",
          state_code: "us_az",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 187,
          is_superagency: null,
          name: "Franklin County Sheriff's Office",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: 185,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 188,
          is_superagency: null,
          name: "Cleveland Police Department",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: 185,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 189,
          is_superagency: null,
          name: "Toledo Police Department",
          settings: [],
          state: "Ohio",
          state_code: "us_oh",
          super_agency_id: 185,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 169,
          is_superagency: null,
          name: "Prisons II",
          settings: [],
          state: "Connecticut",
          state_code: "us_ct",
          super_agency_id: null,
          systems: ["PRISONS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 170,
          is_superagency: null,
          name: "Jails + LE",
          settings: [],
          state: "Connecticut",
          state_code: "us_ct",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT", "JAILS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 175,
          is_superagency: null,
          name: "Courts [DEMO]",
          settings: [],
          state: "Arizona",
          state_code: "us_az",
          super_agency_id: null,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 176,
          is_superagency: null,
          name: "Defense [DEMO]",
          settings: [],
          state: "New York",
          state_code: "us_ny",
          super_agency_id: null,
          systems: ["DEFENSE"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 178,
          is_superagency: null,
          name: "Jails [DEMO]",
          settings: [],
          state: "Alaska",
          state_code: "us_ak",
          super_agency_id: null,
          systems: ["JAILS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 183,
          is_superagency: null,
          name: "Iowa State University Police Department (STAGING)",
          settings: [],
          state: "Iowa",
          state_code: "us_ia",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 191,
          is_superagency: null,
          name: "Lili - Jessica Test",
          settings: [],
          state: "Connecticut",
          state_code: "us_ct",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 207,
          is_superagency: true,
          name: "New Mexico Administrative Office of the Courts",
          settings: [],
          state: "New Mexico",
          state_code: "us_nm",
          super_agency_id: null,
          systems: ["SUPERAGENCY", "COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 209,
          is_superagency: false,
          name: "Ninth Judicial District Curry County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 210,
          is_superagency: false,
          name: "San Juan County Magistrate Court in Aztec",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 211,
          is_superagency: false,
          name: "Socorro County Magistrate Court in Socorro",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 212,
          is_superagency: false,
          name: "Fourth Judicial District Mora County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 213,
          is_superagency: false,
          name: "San Miguel County Magistrate Court in Las Vegas",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 214,
          is_superagency: false,
          name: "Catron County Magistrate Court in Reserve",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 215,
          is_superagency: false,
          name: "Dona Ana County Magistrate Court in Las Cruces",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 216,
          is_superagency: false,
          name: "Fifth Judicial District Chaves County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 217,
          is_superagency: false,
          name: "Bernalillo County Metropolitan Court",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 218,
          is_superagency: false,
          name: "Chaves County Magistrate Court in Roswell",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 219,
          is_superagency: false,
          name: "Seventh Judicial District Catron County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 220,
          is_superagency: false,
          name: "Fifth Judicial District Lea County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 221,
          is_superagency: false,
          name: "Harding County Magistrate Court in Roy",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 222,
          is_superagency: false,
          name: "Seventh Judicial District Socorro County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 223,
          is_superagency: false,
          name: "Thirteenth Judicial District Valencia County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 224,
          is_superagency: false,
          name: "Roosevelt County Magistrate Court in Portales",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 225,
          is_superagency: false,
          name: "Sixth Judicial District Hidalgo County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 226,
          is_superagency: false,
          name: "Lea County Magistrate Court in Jal",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 227,
          is_superagency: false,
          name: "Catron County Magistrate Court in Quemado",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 228,
          is_superagency: false,
          name: "Colfax County Magistrate Court in Springer",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 229,
          is_superagency: false,
          name: "Third Judicial District Dona Ana County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 230,
          is_superagency: false,
          name: "Lea County Magistrate Court in Lovington",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 231,
          is_superagency: false,
          name: "Sierra County Magistrate Court in T or C",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 232,
          is_superagency: false,
          name: "Eleventh Judicial District McKinley County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 233,
          is_superagency: false,
          name: "First Judicial District Rio Arriba County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 234,
          is_superagency: false,
          name: "Guadalupe County Magistrate Court in Santa Rosa",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 235,
          is_superagency: false,
          name: "Tenth Judicial District Quay County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 236,
          is_superagency: false,
          name: "Eddy County Magistrate Court in Carlsbad",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 237,
          is_superagency: false,
          name: "Sixth Judicial District Luna County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 238,
          is_superagency: false,
          name: "Lea County Magistrate Court in Eunice",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 239,
          is_superagency: false,
          name: "Otero County Magistrate Court in Alamogordo",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 240,
          is_superagency: false,
          name: "Hidalgo County Magistrate Court in Lordsburg",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 241,
          is_superagency: false,
          name: "Dona Ana County Magistrate Court in Anthony",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 242,
          is_superagency: false,
          name: "Rio Arriba County Magistrate Court in Espanola",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 243,
          is_superagency: false,
          name: "DeBaca County Magistrate Court in Fort Sumner",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 244,
          is_superagency: false,
          name: "Union County Magistrate Court in Clayton",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 245,
          is_superagency: false,
          name: "Fourth Judicial District San Miguel County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 246,
          is_superagency: false,
          name: "Fifth Judicial District Eddy County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 247,
          is_superagency: false,
          name: "Tenth Judicial District De Baca County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 248,
          is_superagency: false,
          name: "Lea County Magistrate Court in Hobbs",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 249,
          is_superagency: false,
          name: "Quay County Magistrate Court in Tucumcari",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 250,
          is_superagency: false,
          name: "McKinley County Magistrate Court in Gallup",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 251,
          is_superagency: false,
          name: "Thirteenth Judicial District Cibola County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 252,
          is_superagency: false,
          name: "First Judicial District Los Alamos County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 253,
          is_superagency: false,
          name: "Twelfth Judicial District Otero County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 254,
          is_superagency: false,
          name: "Eighth Judicial District Union County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 255,
          is_superagency: false,
          name: "San Juan County Magistrate Court in Farmington",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 256,
          is_superagency: false,
          name: "Santa Fe County Magistrate Court in Santa Fe",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 257,
          is_superagency: false,
          name: "Valencia County Magistrate Court in Los Lunas",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 258,
          is_superagency: false,
          name: "Taos County Magistrate Court in Taos",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 259,
          is_superagency: false,
          name: "Dona Ana County Magistrate Court in Hatch",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 260,
          is_superagency: false,
          name: "Torrance County Magistrate Court in Estancia",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 261,
          is_superagency: false,
          name: "First Judicial District Santa Fe County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 262,
          is_superagency: false,
          name: "Tenth Judicial District Harding County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 263,
          is_superagency: false,
          name: "Colfax County Magistrate Court in Raton",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 264,
          is_superagency: false,
          name: "Seventh Judicial District Sierra County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 265,
          is_superagency: false,
          name: "Lincoln County Magistrate Court in Carrizozo",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 266,
          is_superagency: false,
          name: "Cibola County Magistrae Court in Grants",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 267,
          is_superagency: false,
          name: "Torrance County Magistrate Court in Moriarty",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 268,
          is_superagency: false,
          name: "Sixth Judicial District Grant County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 269,
          is_superagency: false,
          name: "Los Alamos County Magistrate Court in Los Alamos",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 270,
          is_superagency: false,
          name: "Eleventh Judicial District San Juan County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 271,
          is_superagency: false,
          name: "Thirteenth Judicial District Sandoval County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 272,
          is_superagency: false,
          name: "Rio Arriba County Magistrate Court in Chama",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 273,
          is_superagency: false,
          name: "Sandoval County Magistrate Court in Bernalillo",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 274,
          is_superagency: false,
          name: "Eddy County Magistrate Court in Artesia",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 275,
          is_superagency: false,
          name: "Eighth Judicial District Taos County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 276,
          is_superagency: false,
          name: "Seventh Judicial District Torrance County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 277,
          is_superagency: false,
          name: "Luna County Magistrate Court in Deming",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 278,
          is_superagency: false,
          name: "Second Judicial District Bernalillo County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 279,
          is_superagency: false,
          name: "Sandoval County Magistrate Court in Cuba",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 280,
          is_superagency: false,
          name: "Ninth Judicial District Roosevelt County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 281,
          is_superagency: false,
          name: "Mora County Magistrate Court in Mora",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 282,
          is_superagency: false,
          name: "Lincoln County Magistrate Court in Ruidoso",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 283,
          is_superagency: false,
          name: "Fourth Judicial District Guadalupe County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 284,
          is_superagency: false,
          name: "Twelfth Judicial District Lincoln County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 285,
          is_superagency: false,
          name: "Curry County Magistrate Court in Clovis",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 286,
          is_superagency: false,
          name: "Eighth Judicial District Colfax County",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 287,
          is_superagency: false,
          name: "Grant County Magistrate Court in Silver City",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 288,
          is_superagency: false,
          name: "Taos County Magistrate Court in Questa",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 289,
          is_superagency: false,
          name: "Valencia County Magistrate Court in Belen",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 290,
          is_superagency: false,
          name: "Grant County Magistrate Court in Bayard",
          settings: [],
          state: "New Mexico",
          state_code: "US_NM",
          super_agency_id: 207,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
      ],
      auth0_user_id: "auth0|62828175a5229e006fa2290b",
      email: "lili@recidiviz.org",
      id: 18,
      name: "Lili",
    },
    {
      agencies: [
        {
          fips_county_code: "us_ny_new_york",
          id: 148,
          is_superagency: null,
          name: "Defense",
          settings: [],
          state: "New York",
          state_code: "us_ny",
          super_agency_id: null,
          systems: ["DEFENSE"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 153,
          is_superagency: null,
          name: "Supervision",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: [
            "SUPERVISION",
            "PROBATION",
            "PRETRIAL_SUPERVISION",
            "OTHER_SUPERVISION",
          ],
          team: [],
        },
        {
          fips_county_code: "us_ar_baxter",
          id: 168,
          is_superagency: null,
          name: "Supervision III",
          settings: [],
          state: "Arkansas",
          state_code: "us_ar",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION", "PAROLE", "PROBATION"],
          team: [],
        },
        {
          fips_county_code: "us_mi_muskegon",
          id: 162,
          is_superagency: null,
          name: "Muskegon County Prosecutor's Office",
          settings: [],
          state: "Michigan",
          state_code: "us_mi",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: "us_ga_douglas",
          id: 163,
          is_superagency: null,
          name: "Douglas County District Attorney's Office",
          settings: [],
          state: "Georgia",
          state_code: "us_ga",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 164,
          is_superagency: null,
          name: "North Carolina Department of Public Safety (NCDPS)",
          settings: [],
          state: "North Carolina",
          state_code: "us_nc",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION", "PROBATION"],
          team: [],
        },
        {
          fips_county_code: "us_ca_alameda",
          id: 165,
          is_superagency: null,
          name: "San Leandro Police Department",
          settings: [],
          state: "California",
          state_code: "us_ca",
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: "us_az_yavapai",
          id: 166,
          is_superagency: null,
          name: "Yavapai County District Attorney's Office",
          settings: [],
          state: "Arizona",
          state_code: "us_az",
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 147,
          is_superagency: null,
          name: "Law Enforcement",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["LAW_ENFORCEMENT"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 150,
          is_superagency: null,
          name: "Courts",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["COURTS_AND_PRETRIAL"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 149,
          is_superagency: null,
          name: "Prosecution",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["PROSECUTION"],
          team: [],
        },
        {
          fips_county_code: "us_ct_tolland",
          id: 167,
          is_superagency: null,
          name: "Supervision II",
          settings: [],
          state: "Connecticut",
          state_code: "us_ct",
          super_agency_id: null,
          systems: ["PRISONS", "SUPERVISION"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 151,
          is_superagency: null,
          name: "Jails",
          settings: [],
          state: null,
          state_code: null,
          super_agency_id: null,
          systems: ["JAILS"],
          team: [],
        },
        {
          fips_county_code: null,
          id: 152,
          is_superagency: null,
          name: "Prisons",
          settings: [],
          state: "New York",
          state_code: "us_ny",
          super_agency_id: null,
          systems: ["PRISONS"],
          team: [],
        },
      ],
      auth0_user_id: "auth0|62843394cebefb00683be31d",
      email: "terry@recidiviz.org",
      id: 19,
      name: "Terry T",
    },
  ],
};
