// Recidiviz - a data platform for criminal justice reform
// Copyright (C) 2024 Recidiviz, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
// =============================================================================

import type { Meta, StoryObj } from "@storybook/react";

import { DatapointsTableView } from "./DatapointsTableView";

const meta: Meta<typeof DatapointsTableView> = {
  title: "DatapointsTableView",
  component: DatapointsTableView,
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
  },
};

export default meta;
type Story = StoryObj<typeof DatapointsTableView>;

export const Default: Story = {
  args: {
    datapoints: [
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: null,
        disaggregation_display_name: null,
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51716,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 10,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: null,
        disaggregation_display_name: null,
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92718,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 20,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: null,
        disaggregation_display_name: null,
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83427,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 30,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: null,
        disaggregation_display_name: null,
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51716,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 10,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "State Appropriation",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51717,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 10,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "County or Municipal Appropriation",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51718,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Grants",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51719,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Commissary and Fees",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51720,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Contract Beds (Funding)",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51721,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Other Funding",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51722,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Unknown Funding",
        disaggregation_display_name: "Funding Type",
        end_date: "Mon, 01 Feb 2021 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 51723,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3532,
        start_date: "Fri, 01 Jan 2021 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: null,
        disaggregation_display_name: null,
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92718,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 20,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "State Appropriation",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92719,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 20,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "County or Municipal Appropriation",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92720,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Grants",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92721,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Commissary and Fees",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92722,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Contract Beds (Funding)",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92723,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Other Funding",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92724,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Unknown Funding",
        disaggregation_display_name: "Funding Type",
        end_date: "Tue, 01 Feb 2022 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 92725,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3140,
        start_date: "Sat, 01 Jan 2022 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: null,
        disaggregation_display_name: null,
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83427,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 30,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "State Appropriation",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83428,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 30,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "County or Municipal Appropriation",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83429,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Grants",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83430,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Commissary and Fees",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83431,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Contract Beds (Funding)",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83432,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Other Funding",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83433,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 0,
      },
      {
        agency_name: "Clackamas County Jail",
        dimension_display_name: "Unknown Funding",
        disaggregation_display_name: "Funding Type",
        end_date: "Wed, 01 Feb 2023 00:00:00 GMT",
        frequency: "MONTHLY",
        id: 83434,
        is_published: false,
        metric_definition_key: "JAILS_FUNDING",
        metric_display_name: "Funding",
        old_value: null,
        report_id: 3381,
        start_date: "Sun, 01 Jan 2023 00:00:00 GMT",
        value: 0,
      },
    ],
    metricName: "Funding",
    metricFrequency: "MONTHLY",
  },
};
