name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@8348ea7f5d949b08c7f125a44b569c9626b05db3 # v1.7.0
        with:
          github-token: "${{ secrets.HELPERBOT_TOKEN }}"
      - name: Check if auto-merge is allowed
        id: check-auto-merge
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.update-type == 'version-update:semver-patch' &&
          steps.metadata.outputs.dependency-names != ''
        run: |
          echo "Dependencies:"
          echo "${{ steps.metadata.outputs.dependency-names }}"
          if echo "${{ steps.metadata.outputs.dependency-names }}" | grep -q 'babel'; then
            echo "@babel packages found. Skipping auto-merge."
            echo "::set-output name=allow_auto_merge::false"
          else
            echo "No babel packages found. Continuing auto-merge."
            echo "::set-output name=allow_auto_merge::true"
          fi
      - name: Auto-approve for Dependabot PRs
        if: steps.check-auto-merge.outputs.allow_auto_merge == 'true'
        run: gh pr review --approve -b "@Recidiviz/justice-counts - HelperBot is automatically approving this Dependabot PR since it is a patch or minor version update." "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.HELPERBOT_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        if: steps.check-auto-merge.outputs.allow_auto_merge == 'true'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.HELPERBOT_TOKEN}}
