name: CI Tests

on: push

jobs:
  cancel-previous-runs:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          # This clones the repo and checks out the SHA that triggered this action.
          # We set fetch-depth 0 to fetch all branches and history so that merge-base
          # is guaranteed to be able to find the common ancestor with the base branch.
          # See https://github.com/actions/checkout#readme
          fetch-depth: 0
      - name: Yarn caching
        uses: actions/cache@v4
        id: yarn-caching
        with:
          path: "**/node_modules"
          key: yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v2-${{ hashFiles('**/yarn.lock') }}
            yarn-v2-
            yarn-
      - name: Yarn install (justice counts)
        if: steps.yarn-caching.outputs.cache-hit != 'true'
        working-directory: ./
        run: yarn install --frozen-lockfile
      - name: Yarn lint (publisher)
        working-directory: ./publisher
        run: yarn lint
      - name: Yarn lint (agency-dashboard)
        working-directory: ./agency-dashboard
        run: yarn lint
      - name: Yarn lint (common)
        working-directory: ./common
        run: yarn lint
      - name: Yarn test (publisher)
        working-directory: ./publisher
        run: yarn test
      - name: Yarn test (agency-dashboard)
        working-directory: ./agency-dashboard
        run: yarn test
      - name: Yarn test (common)
        working-directory: ./common
        run: yarn test
