name: CI Tests

on: push

permissions:
  contents: read

jobs:
  cancel-previous-runs:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Cancel previous runs
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73 # 0.6.0
        with:
          access_token: ${{ github.token }}

  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "20"
          # This clones the repo and checks out the SHA that triggered this action.
          # We set fetch-depth 0 to fetch all branches and history so that merge-base
          # is guaranteed to be able to find the common ancestor with the base branch.
          # See https://github.com/actions/checkout#readme
          fetch-depth: 0
      - name: Yarn caching
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: yarn-caching
        with:
          path: "**/node_modules"
          key: yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v2-${{ hashFiles('**/yarn.lock') }}
            yarn-v2-
            yarn-
      - name: Yarn install (justice counts)
        if: steps.yarn-caching.outputs.cache-hit != 'true'
        working-directory: ./
        run: yarn install --frozen-lockfile
      - name: Yarn lint (publisher)
        working-directory: ./publisher
        run: yarn lint
      - name: Yarn lint (agency-dashboard)
        working-directory: ./agency-dashboard
        run: yarn lint
      - name: Yarn lint (common)
        working-directory: ./common
        run: yarn lint
      - name: Yarn test (publisher)
        working-directory: ./publisher
        run: yarn test
      - name: Yarn test (agency-dashboard)
        working-directory: ./agency-dashboard
        run: yarn test
      - name: Yarn test (common)
        working-directory: ./common
        run: yarn test
