name: Deploy to Playtest

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      service_name:
        description: "Service name."
        required: true
        default: "publisher-web"
        type: choice
        options:
          - publisher-web
          - agency-dashboard-web
      url_tag:
        description: "Playtest URL tag. Must first be a registered Publisher Auth0 URL."
        required: true
        default: "test"

jobs:
  playtest:
    permissions:
      contents: read
      id-token: write
    name: Deploy to Playtest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Authorize Github Actions
        uses: "google-github-actions/auth@v2"
        with:
          service_account: justice-counts-staging@justice-counts-staging.iam.gserviceaccount.com
          workload_identity_provider: projects/840995502642/locations/global/workloadIdentityPools/github/providers/github-actions
          project_id: "justice-counts-staging"
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest
      - name: Extract Branch Name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Start Deploy-to-playtesting Cloud Build trigger
        run: |
          gcloud --quiet builds triggers run Deploy-to-playtesting \
          --branch=${{ steps.extract_branch.outputs.branch }} \
          --substitutions _SERVICE_NAME="publisher-web",_URL_TAG="test",_SUBDIRECTORY=playtesting,_FRONTEND_URL=https://github.com/Recidiviz/justice-counts/archive/main.tar.gz

      # --substitutions _SERVICE_NAME=${{ github.event.inputs.service_name }},_URL_TAG=${{ github.event.inputs.url_tag }},_SUBDIRECTORY=playtesting,_FRONTEND_URL=https://github.com/Recidiviz/justice-counts/archive/main.tar.gz
     
      # - name: Bot Comment
      #   if: ${{ success() }}
      #   run: gh pr comment ${{ steps.extract_branch.outputs.branch }} -b "Playtest deployment was successfully triggered. Full deployment usually takes 5 minutes. Your playtest link is https://${{ github.event.inputs.url_tag }}---publisher-web-b47yvyxs3q-uc.a.run.app/"
        # env:
        #   GITHUB_TOKEN: ${{secrets.HELPERBOT_TOKEN}}
