name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: mheap/github-action-required-labels@d2892166405e47deea29d2052ab4cca1382df41e # v1.2.0
        with:
          mode: minimum
          count: 1
          labels: "Type: Bug, Type: Feature, Type: Breaking Change, Type: Non-breaking refactor, Type: Configuration Change, Type: Dependency Upgrade"
