name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "Type: Bug, Type: Feature, Type: Breaking Change, Type: Non-breaking refactor, Type: Configuration Change, Type: Dependency Upgrade"
